#!/usr/bin/env python3
"""
Convert blocks.json into an Excel spreadsheet.

Input JSON format:
{
    "22": {
        "active": true,
        "block_captain": true,
        "addresses": [
            "19969 Scotland Dr, Saratoga, CA",
            "19975 Glasgow Dr, Saratoga, CA"
        ]
    }
}

Output columns:
    Index | Street Address | Block # | Block Captain

Usage:
    python3 blocks_to_excel.py blocks.json
    python3 blocks_to_excel.py blocks.json -o neighborhood_blocks.xlsx

Dependency:
    pip install openpyxl
"""

import argparse
import json
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


def block_sort_key(item):
    block_id, _ = item
    try:
        return (0, int(block_id))
    except ValueError:
        return (1, block_id)


def load_rows(json_path):
    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    rows = []
    index = 1

    for block_id, info in sorted(data.items(), key=block_sort_key):
        # New format generated by saratoga_block_addresses_county_v9/v10.
        # Default to False if the field is absent, so the spreadsheet does not
        # falsely claim a captain exists.
        has_captain = bool(info.get("block_captain", False))

        for address in info.get("addresses", []):
            address = str(address).strip()
            if not address:
                continue

            rows.append([
                index,
                address,
                int(block_id) if str(block_id).isdigit() else str(block_id),
                "Yes" if has_captain else "No",
            ])
            index += 1

    return rows


def write_excel(rows, output_path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Blocks"

    headers = [
        "Index",
        "Street Address",
        "Block #",
        "Block Captain",
    ]

    ws.append(headers)

    for row in rows:
        ws.append(row)

    # Header styling.
    header_fill = PatternFill("solid", fgColor="1F4E78")
    header_font = Font(color="FFFFFF", bold=True)

    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # Body alignment.
    for row in ws.iter_rows(min_row=2):
        row[0].alignment = Alignment(horizontal="center")
        row[2].alignment = Alignment(horizontal="center")
        row[3].alignment = Alignment(horizontal="center")

    # Useful spreadsheet behavior.
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    # Fixed, readable widths.
    widths = {
        "A": 10,
        "B": 42,
        "C": 12,
        "D": 18,
    }

    for col, width in widths.items():
        ws.column_dimensions[col].width = width

    # Slightly taller header row.
    ws.row_dimensions[1].height = 22

    wb.save(output_path)


def main():
    parser = argparse.ArgumentParser(
        description="Convert blocks.json to a formatted Excel spreadsheet."
    )
    parser.add_argument(
        "blocks_json",
        type=Path,
        help="Input blocks.json file",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("blocks.xlsx"),
        help="Output .xlsx file (default: blocks.xlsx)",
    )

    args = parser.parse_args()

    if not args.blocks_json.exists():
        raise SystemExit(f"Input file does not exist: {args.blocks_json}")

    rows = load_rows(args.blocks_json)
    write_excel(rows, args.output)

    print(f"Wrote {len(rows)} addresses to {args.output.resolve()}")


if __name__ == "__main__":
    main()
